import ROOT
items = [
  {"name":"btag",
   "mode":"range",
   "before":5,
   "after":8,
   "y1":0.001,
   "y2":1e3,
   "style":1,
   "color":ROOT.kBlack,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":2,
   "y":2.5*1e3,
   "size":0.03,
   "text":"N_{b-tag} = 0",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":0,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":5.5,
   "y":2.5*1e3,
   "size":0.03,
   "text":"N_{b-tag} = 1",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":0,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":9.5,
   "y":2.5*1e3,
   "size":0.03,
   "text":"N_{b-tag} > 1",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":0,
  },

]
