import ROOT
items = [
  {"name":"btag",
   "mode":"range",
   "before":7,
   "after":12,
   "y1":0.001,
   "y2":18,
   "style":1,
   "color":ROOT.kBlack,
   "widht":3,
   "doOnRatio":True,
  },
{"name":"btag",
   "mode":"range",
   "before":13,
   "after":18,
   "y1":0.001,
   "y2":18,
   "style":1,
   "color":ROOT.kBlack,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":2.5,
   "y":15,
   "size":0.03,
   "text":"BDT_{CP} < 0.14",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":9.5,
   "y":15,
   "size":0.03,
   "text":"0.14 < BDT_{CP} < 0.18",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":14.5,
   "y":15,
   "size":0.03,
   "text":"0.18 < BDT_{CP} < 0.24",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  },
 {"name":"lbtg",
   "mode":"text",
   "x":20.5,
   "y":15,
   "size":0.03,
   "text":"BDT_{CP} > 0.24",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  }
]
