import ROOT
items = [
  {"name":"btag",
   "mode":"range",
   "before":14,
   "after":26,
   "y1":0.001,
   "y2":18,
   "style":1,
   "color":ROOT.kBlack,
   "widht":3,
   "doOnRatio":True,
  },
{"name":"btag",
   "mode":"range",
   "before":27,
   "after":39,
   "y1":0.001,
   "y2":18,
   "style":1,
   "color":ROOT.kBlack,
   "widht":3,
   "doOnRatio":True,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":6.5,
   "y":25,
   "size":0.03,
   "text":"BDT_{CP} < 0.13",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":20,
   "y":24,
   "size":0.03,
   "text":"0.13 < BDT_{CP} < 0.17",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  },
  {"name":"lbtg",
   "mode":"text",
   "x":35,
   "y":24,
   "size":0.03,
   "text":"0.17 < BDT_{CP} < 0.22",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  },
 {"name":"lbtg",
   "mode":"text",
   "x":45,
   "y":25,
   "size":0.03,
   "text":"BDT_{CP} > 0.22",
   "color":ROOT.kBlack,
   "doOnRatio":True,
   "angle":90,
  }
]
